name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build with Buildozer
        uses: ArtemSerebrennkov/buildozer-action@v1
        with:
          buildozer_version: stable
          python_version: 3.8

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: Ziyad-APK-Result
          path: bin/*.apk
